---
title: "Regional cluster"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---


```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup_obs.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths, include = FALSE}

# only path_observations needs to be changed to model
path_observations <-
  paste(path_root, "/observations/", sep = "")

path_preprocessing    <-
  paste(path_observations, "preprocessing/", sep = "")

```

```{r select_basin_mask, include=FALSE}

basinmask <- basinmask %>% 
  select(-c(MLR_basins, basin))

```

```{r load_libraries_specific, include=FALSE}

library(factoextra)
library(NbClust)

```

# Data source

Currently, following data sets and predictor variables are used for clustering:

- GLODAPv2_2016b_MappedClimatologies
  - Phosphate
  - Oxygen 
  - Cant
  - temperature

```{r load_GLODAPv2_2016b_MappedClimatologies}

variables <-
  c("oxygen", "PO4", "Cant", "temperature")

# i_variable <- variables[1]

for (i_variable in variables) {
  temp <- read_csv(paste(
    path_preprocessing,
    paste("GLODAPv2_2016_MappedClimatology_", i_variable, ".csv", sep = ""),
    sep = ""
  ))
  
  if (exists("GLODAP_predictors")) {
    GLODAP_predictors <- full_join(GLODAP_predictors, temp)
  }
  
  if (!exists("GLODAP_predictors")) {
    GLODAP_predictors <- temp
  }
}

rm(temp, i_variable, variables)

GLODAP_predictors <- GLODAP_predictors %>%
  rename(phosphate = PO4,
         temp = temperature) %>% 
  select(-basin_AIP)

# removed na's attributable to slightly different coverage of predictor fields
GLODAP_predictors <- GLODAP_predictors %>%
  drop_na()

```

# Scaling predictors

```{r cluster_predictors}

cluster_predictors <- GLODAP_predictors %>% 
  select(oxygen, phosphate, Cant, temp)

cluster_predictors <- cluster_predictors %>% 
  scale() %>% 
  as_tibble()

cluster_predictors %>% 
  pivot_longer(oxygen:temp) %>% 
  ggplot(aes(value)) +
  geom_histogram() +
  facet_wrap(~ name)

```


# Number of clusters

Based on a random subset of 1000 data points, the optimum number of clusters was inspected as elbow plot.

```{r determine_number_of_cluster}

cluster_predictors_sub <- cluster_predictors %>% 
  sample_n(1e3)


# https://rpubs.com/pg2000in/OptimumClusters

fviz_nbclust(cluster_predictors_sub, kmeans, method = "wss")
fviz_nbclust(cluster_predictors_sub, kmeans, method = "silhouette")
fviz_nbclust(cluster_predictors_sub, kmeans, method = "gap_stat")

# http://www.sthda.com/english/articles/29-cluster-validation-essentials/96-determiningthe-optimal-number-of-clusters-3-must-know-methods/

# nb <- NbClust(cluster_predictors_sub, distance = "euclidean", min.nc = 2,
#         max.nc = 10, method = "kmeans")
# 
# fviz_nbclust(nb)


```

# Clustering

```{r kmeans_clustering}

clusters <- kmeans(cluster_predictors,
       centers = 6,
       iter.max = 10)

GLODAP_predictors <- GLODAP_predictors %>% 
  mutate(cluster = as.factor(clusters$cluster))


```

## Maps

```{r cluster_maps}

map +
  geom_raster(data = GLODAP_predictors %>%
                filter(depth %in% c(0,100,500,1000, 2000, 5000)),
              aes(lon, lat, fill = cluster)) +
  # scale_fill_brewer(palette = "Set1") +
  scale_fill_viridis_d() +
  facet_wrap(~ depth, ncol = 2)


```

## Zonal sections

```{r cluster_sections, fig.asp=1}

ggplot(
  data = GLODAP_predictors %>%
    filter(lon %in% params_global$longitude_sections_basin,
           depth <= 2000),
  aes(lat, depth, fill = cluster)
) +
  geom_raster() +
  scale_fill_viridis_d() +
  scale_y_reverse() +
  coord_cartesian(expand = 0) +
  facet_wrap(~ lon, ncol = 1)


```



