---
title: "Surface flux products"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---


```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths, include=FALSE}
path_reccap2_surface_co2   <- "/nfs/kryo/work/updata/reccap2/Surface_CO2"
path_seaflux_surface_co2   <- "/nfs/kryo/work/updata/pco2_seaflux/"
path_preprocessing    <- paste(path_root, "/observations/preprocessing/", sep = "")
```

```{r load_libraries_specific, include=FALSE}
library(tidync)
library(lubridate)
```

# Read data

## fgco2 global integrals

### RECCAP2

```{r read_fgco2_RECCAP2}

products <- list.files(path_reccap2_surface_co2)

products <-
  products[!str_detect(products, pattern = "\\.")]

# Remove data sets that do not meet formatting requirements

products <-
  products[!str_detect(products, pattern = "JMAMLR_v20210312")]

products <-
  products[!str_detect(products, pattern = "JMAMLR_v20211202")]

products <-
  products[!str_detect(products, pattern = "LDEO_2021_clim_RECCAP2_v20210702")]

products <-
  products[!str_detect(products, pattern = "spco2_LDEO_HPD_1985-2018_v20211210")]

products <-
  products[!str_detect(products, pattern = "NIES-nn_v202011")]

products <-
  products[!str_detect(products, pattern = "SOMFFN_v20211121")]

products <-
  products[!str_detect(products, pattern = "AOML_EXTRAT_v20211130")]

### loop

for (i_products in products) {
  # i_products <- products[5]
  
  path_product <- paste(path_reccap2_surface_co2,
                        i_products,
                        sep = "/")
  
  product_file_name <-
    list.files(path_product, pattern = "fgco2_glob")
  
  RECCAP2 <-
    tidync(paste(path_product,
                 product_file_name,
                 sep = "/"))
  
  RECCAP2 <- RECCAP2 %>%
    hyper_tibble()
  
  RECCAP2 <- RECCAP2 %>%
    mutate(product = i_products)
  
  if (exists("RECCAP2_all")) {
    RECCAP2_all <- bind_rows(RECCAP2_all, RECCAP2)
  }
  
  if (!exists("RECCAP2_all")) {
    RECCAP2_all <- RECCAP2
  }
  
}



```

### Seaflux

```{r read_seaflux_data}

SeaFlux_file_name <- paste0(path_seaflux_surface_co2,
                             "SeaFlux_v2021.04_fgco2_global.nc")

SeaFlux <-
  tidync(SeaFlux_file_name) %>% 
  hyper_tibble()

ncmeta::nc_atts(SeaFlux_file_name)
ncmeta::nc_atts(SeaFlux_file_name, "time") %>% tidyr::unnest(cols = c(value))


SeaFlux <- SeaFlux %>% 
  mutate(date = as.Date(time, origin = '1982-01-15'),
         year = year(date))


```

# Timeseries

## RECCAP2

```{r fgco2_time_series_RECCAP2}

RECCAP2_all <- RECCAP2_all %>% 
  mutate(date = as.Date(time, origin = '1980-01-01'),
         year = year(date)) %>% 
  select(product, year, date, fgco2_glob)


RECCAP2_all %>% 
  ggplot(aes(date, fgco2_glob, col=product)) +
  geom_line() +
  theme(legend.position = "bottom")


RECCAP2_all_annual <- RECCAP2_all %>% 
  group_by(year, product) %>% 
  summarise(fgco2_glob = mean(fgco2_glob)) %>% 
  ungroup()
  

RECCAP2_all_annual %>% 
  ggplot(aes(year, fgco2_glob, col=product)) +
  geom_line() +
  theme(legend.position = "bottom")

RECCAP2_all_annual_cum_1994 <- RECCAP2_all_annual %>% 
  filter(year >= 1994) %>% 
  arrange(year) %>% 
  group_by(product) %>% 
  mutate(fgco2_glob_cum = cumsum(fgco2_glob)) %>% 
  ungroup()
  

RECCAP2_all_annual_cum_1994 %>%
  ggplot(aes(year, fgco2_glob_cum, col = product)) +
  geom_line() +
  geom_point(shape = 21, fill = "white") +
  theme(legend.position = "bottom")


RECCAP2_all_annual_ensemble <- RECCAP2_all_annual %>%
  filter(product != "UOEX_Wat20_1985_2019_v20211204") %>% 
  group_by(year) %>%
  summarise(fgco2_glob_sd = sd(fgco2_glob),
            fgco2_glob = mean(fgco2_glob)) %>%
  ungroup()

ggplot() +
  geom_ribbon(
    data =
      RECCAP2_all_annual_ensemble,
    aes(
      year,
      ymax = fgco2_glob + fgco2_glob_sd,
      ymin = fgco2_glob - fgco2_glob_sd,
      fill = "ensemble SD"
    ), alpha = 0.3
  ) +
  geom_line(data =
              RECCAP2_all_annual,
            aes(year, fgco2_glob, group = product, col = "individual products")) +
  geom_line(data =
              RECCAP2_all_annual_ensemble,
            aes(year, fgco2_glob, col = "ensemble mean"), size = 1) +
  scale_fill_manual(values = "red") +
  scale_color_manual(values = c("red", "grey50")) +
  theme(legend.position = "bottom",
        legend.title = element_blank())

```


## Seaflux

```{r fgco2_time_series_seaflux}

SeaFlux <- SeaFlux %>% 
  mutate(fgco2_glob = -fgco2_global) %>% 
  select(product, wind, year, date, fgco2_glob)


SeaFlux %>% 
  ggplot(aes(date, fgco2_glob, col=wind)) +
  geom_line() +
  theme(legend.position = "bottom") +
  facet_wrap(~ product)


SeaFlux_annual <- SeaFlux %>% 
  filter(wind %in% c("CCMP2", "ERA5", "JRA55")) %>% 
  group_by(year, product) %>% 
  summarise(fgco2_glob = mean(fgco2_glob)) %>% 
  ungroup()
  

SeaFlux_annual %>% 
  ggplot(aes(year, fgco2_glob, col=product)) +
  geom_line() +
  theme(legend.position = "bottom")

SeaFlux_annual_cum_1994 <- SeaFlux_annual %>% 
  filter(year >= 1994) %>% 
  arrange(year) %>% 
  group_by(product) %>% 
  mutate(fgco2_glob_cum = cumsum(fgco2_glob)) %>% 
  ungroup()
  

SeaFlux_annual_cum_1994 %>%
  ggplot(aes(year, fgco2_glob_cum, col = product)) +
  geom_line() +
  geom_point(shape = 21, fill = "white") +
  theme(legend.position = "bottom")


SeaFlux_annual_ensemble <- SeaFlux_annual %>%
  group_by(year) %>%
  summarise(fgco2_glob_sd = sd(fgco2_glob),
            fgco2_glob = mean(fgco2_glob)) %>%
  ungroup()

ggplot() +
  geom_ribbon(
    data =
      SeaFlux_annual_ensemble,
    aes(
      year,
      ymax = fgco2_glob + fgco2_glob_sd,
      ymin = fgco2_glob - fgco2_glob_sd,
      fill = "ensemble SD"
    ), alpha = 0.3
  ) +
  geom_line(data =
              SeaFlux_annual,
            aes(year, fgco2_glob, group = product, col = "individual products")) +
  geom_line(data =
              SeaFlux_annual_ensemble,
            aes(year, fgco2_glob, col = "ensemble mean"), size = 1) +
  scale_fill_manual(values = "red") +
  scale_color_manual(values = c("red", "grey50")) +
  theme(legend.position = "bottom",
        legend.title = element_blank())

```

## Comparison


```{r fgco2_time_series_comparison}

ggplot() +
  geom_line(data = SeaFlux_annual,
            aes(year, fgco2_glob, group = product,
                col = "Seaflux")) +
  geom_line(data = RECCAP2_all_annual,
            aes(year, fgco2_glob, group = product,
                col = "RECCAP2")) +
  scale_color_brewer(palette = "Dark2") +
  theme(legend.position = "bottom",
        legend.title = element_blank())

ggplot() +
  geom_line(data = SeaFlux_annual_cum_1994,
            aes(year, fgco2_glob_cum, group = product,
                col = "Seaflux")) +
  geom_line(data = RECCAP2_all_annual_cum_1994,
            aes(year, fgco2_glob_cum, group = product,
                col = "RECCAP2")) +
  scale_color_brewer(palette = "Dark2") +
  theme(legend.position = "bottom",
        legend.title = element_blank())


```



# Write files

```{r write_fgco2_files}

RECCAP2_all %>%
  write_csv(paste0(path_preprocessing,
                   "fgco2_glob_RECCAP2_all.csv"))

RECCAP2_all_annual %>%
  write_csv(paste0(path_preprocessing,
                   "fgco2_glob_RECCAP2_all_annual.csv"))

SeaFlux %>%
  write_csv(paste0(path_preprocessing,
                   "fgco2_glob_Seaflux.csv"))

SeaFlux_annual %>%
  write_csv(paste0(path_preprocessing,
                   "fgco2_glob_Seaflux_annual.csv"))



```

