---
title: "GLODAPv2_2016: Mapped Climatologies"
author: "Jens Daniel Müller"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---


```{r parent, child = "/nfs/kryo/work/jenmueller/emlr_cant/utilities/setup.Rmd"}
# this chunk runs the code stored in setup.Rmd
# if required, please refer to instructions given here:
# https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html
```

```{r define_paths, include=FALSE}
path_updata   <- "/nfs/kryo/work/updata/"
path_preprocessing    <- paste(path_root, "/observations/preprocessing/", sep = "")
```

```{r load_libraries_specific, include=FALSE}
library(tidync)
library(lubridate)
library(marelac)
library(broom)
library(seacarb)
library(zoo)
```

# Read source files


```{r prepare_basin_mask}

basinmask_5 <- basinmask %>% 
  filter(MLR_basins == "5") %>% 
  select(lat, lon, basin)

basinmask <- basinmask %>% 
  filter(MLR_basins == "2") %>% 
  select(lat, lon, basin_AIP)


```

## OceanSODA

```{r read_OceanSODA}

OceanSODA <-
  tidync(paste(
    path_updata,
    "pco2_oceansoda-ethz/OS-ETHZ-GRaCER-v2021a_1982-2020.nc",
    sep = ""
  ))

OceanSODA <- OceanSODA %>%
  hyper_tibble()

OceanSODA <- OceanSODA %>%
  mutate(date = as.Date(time, origin = '1982-01-15'),
         year = year(date))

OceanSODA <- OceanSODA %>%
  select(year, date, lat, lon,
         sal = salinity, temp = temperature,
         tco2 = dic, talk, 
         rev_fac = revelle_factor,
         pCO2 = spco2,
         fgco2)


```

## SeaFlux

```{r read_SeaFlux}

path_SeaFlux <- 
paste0(path_updata,"pco2_seaflux/")

icefrac <-
  tidync(paste0(path_SeaFlux,
                "SeaFluxV2021.01_icefrac_1988-2018.nc")) %>% 
  hyper_tibble()

icefrac <- icefrac %>%
  mutate(date = as.Date(time, origin = '1988-01-15'),
         year = year(date))

kw <-
  tidync(paste0(path_SeaFlux,
                "SeaFluxV2021.01_kwScaled16.5cmhr_1988-2018.nc"))

kw <- kw %>% 
  hyper_filter(wind = wind == "ERA5") %>% 
  hyper_tibble() %>% 
  select(-wind)


pCO2atm <-
  tidync(paste0(path_SeaFlux,
                "SeaFluxV2021.01_pCO2atm_NOAAmbl_ERA5mslp_1988-2018.nc")) %>% 
  hyper_tibble()

sol <-
  tidync(paste0(path_SeaFlux,
                "SeaFluxV2021.01_solWeis74.nc")) %>% 
  hyper_tibble()


```

## Join data

```{r join_data}

all_variables <- full_join(icefrac, kw)
all_variables <- full_join(all_variables, pCO2atm)
all_variables <- full_join(all_variables, sol)

OceanSODA <- inner_join(all_variables,
                        OceanSODA)

OceanSODA <- OceanSODA %>%
  mutate(lon = if_else(lon < 20, lon + 360, lon))

OceanSODA <- inner_join(OceanSODA, basinmask)

OceanSODA <- OceanSODA %>% 
  select(-time)

```

## Atm pCO2

```{r read_atm_pco2}

# Note: this file is only created downstream in read_CO2_atm.Rmd
co2_atm_reccap2 <-
  read_csv(paste(path_preprocessing,
                 "co2_atm_reccap2.csv",
                 sep = ""))

```


# Air-sea disequilibrium

```{r air_sea_disequilibrium}

all_variables <- OceanSODA %>%
  select(
    time_mon = date,
    lon,
    lat,
    spco2 = pCO2,
    pco2atm = pCO2atm,
    fice = ice,
    alpha = sol_Weiss74,
    Kw = kw_scaled
  ) %>%
  drop_na()

all_variables <- all_variables %>%
  mutate(area = earth_surf(lat = lat))

mol_to_g <- 12.011
P <- 1e-15
cm_to_m <- 100
hr_to_yr <- 24 * 365

unit_conversion_to_PgCyr <- mol_to_g * P * hr_to_yr / cm_to_m

all_variables <- all_variables %>%
  mutate(
    delta_pco2 = spco2 - pco2atm,
    scale = area * Kw * alpha * (1 - fice),
    fgco2 = delta_pco2 * scale
  )

delta_pco2_monthly <- all_variables %>%
  group_by(time_mon) %>%
  summarise(
    scaling_glob = sum(scale),
    fgco2_glob = sum(fgco2),
    delta_pco2_glob = fgco2_glob / scaling_glob
  ) %>%
  ungroup() %>%
  mutate(fgco2_glob = fgco2_glob * unit_conversion_to_PgCyr)

delta_pco2_annual <- delta_pco2_monthly %>%
  mutate(year = year(time_mon)) %>%
  group_by(year) %>%
  summarise(
    scaling_glob = mean(scaling_glob),
    fgco2_glob = mean(fgco2_glob),
    delta_pco2_glob = mean(delta_pco2_glob)
  ) %>%
  ungroup()

delta_pco2_annual <- delta_pco2_annual %>% 
  mutate(fgco2_glob_roll = zoo::rollmean(fgco2_glob, 10, fill = NA))


ggplot() +
  geom_path(data = delta_pco2_monthly,
            aes(decimal_date(time_mon), delta_pco2_glob, col = "monthly")) +
  geom_path(data = delta_pco2_annual,
            aes(year, delta_pco2_glob, col = "annual")) +
  scale_color_brewer(palette = "Set1", name = "Average") +
  labs(x = "year")

print(
  ggplot() +
    geom_path(data = delta_pco2_monthly,
              aes(decimal_date(time_mon), fgco2_glob, col = "monthly")) +
    geom_path(data = delta_pco2_annual,
              aes(year, fgco2_glob, col = "annual")) +
    geom_path(data = delta_pco2_annual,
              aes(year, fgco2_glob_roll, col = "5yr roll ave")) +
    scale_color_brewer(palette = "Set1", name = "Average") +
    labs(x = "year")
)

print(ggplot() +
        geom_path(data = delta_pco2_annual,
                  aes(
                    year,
                    scaling_glob * unit_conversion_to_PgCyr
                  )))

print(
  ggplot() +
    geom_path(
      data = delta_pco2_annual,
      aes(
        year,
        scaling_glob * delta_pco2_glob * unit_conversion_to_PgCyr,
        col = "scaled"
      )
    ) +
    geom_path(data = delta_pco2_annual,
              aes(year, fgco2_glob, col = "integrated")) +
    scale_color_brewer(palette = "Set1", name = "Estimate") +
    scale_y_continuous(name = "Air-sea flux [PgC yr-1]") +
    labs(x = "year")
)


```

# Compute climatologies


```{r prepare_OceanSODA_climatologies}

# calculate annual averaged fields
OceanSODA_annual_all <- OceanSODA %>%
  mutate(tco2_over_pCO2 = tco2 / pCO2) %>%
  group_by(year, lat, lon) %>%
  summarise_if(is.numeric, mean, na.rm = TRUE) %>%
  ungroup() %>%
  mutate(grid_area = earth_surf(lat = lat))

# grid data in space and time, remove data outside grid
OceanSODA_annual <- OceanSODA_annual_all %>%
  mutate(
    grid_area = earth_surf(lat = lat),
    lat_bands = cut(lat, seq(-80, 80, 20)),
    decade = cut(year,
                 seq(1990, 2020, 10),
                 right = FALSE,
                 labels = c("1990-1999", "2000-2009", "2010-2019"))
  ) %>%
  drop_na()


# calculate climatological fields
OceanSODA_clim <- OceanSODA_annual %>%
  select(-c(grid_area)) %>% 
  group_by(lat, lon) %>%
  summarise_if(is.numeric, mean, na.rm = TRUE) %>% 
  ungroup()

# calculate decadal climatological fields
OceanSODA_clim_decadal <- OceanSODA_annual %>%
  select(-c(grid_area)) %>% 
  group_by(lat, lon, decade) %>%
  summarise_if(is.numeric, mean, na.rm = TRUE) %>% 
  ungroup()


# calculate area-weighted annual mean within latitude band 
OceanSODA_annual_lat <- OceanSODA_annual %>%
  pivot_longer(sal:tco2_over_pCO2,
               names_to = "parameter",
               values_to = "value") %>%
  mutate(value_area = value * grid_area) %>% 
  group_by(year, lat_bands, decade, parameter) %>%
  summarise(
    area_total = sum(grid_area),
    value_area_total = sum(value_area),
    value_area_ave = value_area_total / area_total
  ) %>%
  ungroup() %>% 
  select(-c(area_total,value_area_total))


# fit decadel linear trends per latitude band
OceanSODA_annual_lat_trend <- OceanSODA_annual_lat %>% 
  nest(data = -c(decade, lat_bands, parameter)) %>% 
  mutate(tidy = map(data,
                    ~tidy(lm(value_area_ave ~ year, data = .x)))) %>% 
  select(-data) %>% 
  unnest(tidy)


# calculate area-weighted annual mean globally
OceanSODA_annual_glob <- OceanSODA_annual %>%
  pivot_longer(sal:tco2_over_pCO2,
               names_to = "parameter",
               values_to = "value") %>%
  mutate(value_area = value * grid_area) %>% 
  group_by(year, decade, parameter) %>%
  summarise(
    area_total = sum(grid_area),
    value_area_total = sum(value_area),
    value_area_ave = value_area_total / area_total
  ) %>%
  ungroup() %>% 
  select(-c(area_total,value_area_total))


# fit decadel linear trends globally
OceanSODA_annual_glob_trend <- OceanSODA_annual_glob %>% 
  nest(data = -c(decade, parameter)) %>% 
  mutate(tidy = map(data,
                    ~tidy(lm(value_area_ave ~ year, data = .x)))) %>% 
  select(-data) %>% 
  unnest(tidy)


#regionall integrated air sea fluxes

OceanSODA_annual_5 <- left_join(basinmask_5,
                                OceanSODA_annual_all)

# calculate area-weighted annual mean globally
OceanSODA_annual_5 <- OceanSODA_annual_5 %>%
  pivot_longer(sal:tco2_over_pCO2,
               names_to = "parameter",
               values_to = "value") %>%
  mutate(value_area = value * grid_area) %>% 
  group_by(year, parameter, basin) %>%
  summarise(
    area_total = sum(grid_area, na.rm = TRUE),
    value_area_total = sum(value_area, na.rm = TRUE),
    value_area_ave = value_area_total / area_total
  ) %>%
  ungroup() %>% 
  select(-c(area_total,value_area_total))


```

```{r revelle_factor_time_series}

map + 
  geom_tile(data = OceanSODA_clim,
            aes(lon, lat, fill = as.factor(year)))

pco2_atm_2004 <- co2_atm_reccap2 %>% 
  filter(year == 2004) %>% 
  pull(pCO2)

co2_atm_reccap2 <- co2_atm_reccap2 %>% 
  mutate(delta_pCO2_hist = pCO2 - pco2_atm_2004)

co2_atm_reccap2_decade <- co2_atm_reccap2 %>% 
  filter(year > 1900) %>% 
  mutate(year = ymd(paste(year, "-06-01"))) %>% 
  mutate(decade = floor_date(year, years(10))) %>% 
  group_by(decade) %>% 
  summarise(delta_pCO2_hist = mean(delta_pCO2_hist)) %>% 
  ungroup()

co2_atm_reccap2_decade %>% 
  ggplot(aes(decade, delta_pCO2_hist)) +
  geom_point() +
  geom_path()

OceanSODA_revelle_hist <- expand_grid(
  co2_atm_reccap2_decade,
  OceanSODA_clim
)

OceanSODA_revelle_hist <- OceanSODA_revelle_hist %>% 
  mutate(pCO2 = pCO2 + delta_pCO2_hist)

map + 
  geom_tile(data = OceanSODA_revelle_hist,
            aes(lon, lat, fill = pCO2)) +
  facet_wrap(~ decade) +
  scale_fill_viridis_c()


OceanSODA_revelle_hist <- OceanSODA_revelle_hist %>% 
  mutate(
    rev_fac = buffer(
      flag = 24,
      var1 = pCO2,
      var2 = talk * 1e-6,
      S = sal,
      T = temp,
      P = 0,
      k1k2 = "l"
    )$BetaD
  )

map + 
  geom_tile(data = OceanSODA_revelle_hist,
            aes(lon, lat, fill = rev_fac)) +
  facet_wrap(~ decade) +
  scale_fill_viridis_c()

OceanSODA_revelle_hist_time_series <- OceanSODA_revelle_hist %>% 
  mutate(area = earth_surf(lat, lon),
         rev_fac_scaled = rev_fac * area) %>% 
  group_by(decade) %>% 
  summarise(rev_fac = sum(rev_fac_scaled) / sum(area)) %>% 
  ungroup()

OceanSODA_revelle_hist_time_series %>% 
  ggplot(aes(decade, rev_fac))+
  geom_point() + 
  geom_path()


```




# Write files

```{r write_WOA18_nuts_O2_predictor_file}

OceanSODA_annual_all %>%
  write_csv(paste0(path_preprocessing,
                   "OceanSODA.csv"))

OceanSODA_clim %>%
  write_csv(paste0(path_preprocessing,
                   "OceanSODA_climatology.csv"))

OceanSODA_revelle_hist_time_series %>%
  write_csv(paste0(path_preprocessing,
                   "OceanSODA_revelle_hist_time_series.csv"))

delta_pco2_annual %>%
  select(-c(scaling_glob, fgco2_glob)) %>%
  write_csv(paste0(path_preprocessing,
                   "OceanSODA_disequilibrium_annual.csv"))


```



# Control plots

```{r OceanSODA_control_plots, fig.asp=0.5}

map +
  geom_raster(data = OceanSODA_annual %>%
                filter(year == 2010), aes(lon, lat, fill = lat_bands)) +
  scale_fill_brewer(palette = "Spectral") +
  labs(title = "Year: 2010")

map +
  geom_raster(data = OceanSODA_annual %>%
                filter(year == 2010), aes(lon, lat, fill = grid_area)) +
  scale_fill_viridis_c() +
  labs(title = "Year: 2010")


```


# Maps

## Climatology

```{r climatology_maps, fig.asp=0.5}

unique(OceanSODA_clim$year)

OceanSODA_clim %>%
  pivot_longer(sal:tco2_over_pCO2,
               names_to = "parameter",
               values_to = "value") %>%
  group_split(parameter) %>%
  # head(1) %>%
  map( ~ map +
         geom_raster(data = .x,
                     aes(lon, lat, fill = value)) +
         scale_fill_viridis_c(name = unique(.x$parameter)))


```

## Decadal climatology

```{r climatology_maps_decadal, fig.asp=1}

OceanSODA_clim_decadal %>%
  pivot_longer(sal:tco2_over_pCO2,
               names_to = "parameter",
               values_to = "value") %>%
  group_split(parameter) %>%
  # head(1) %>%
  map( ~ map +
         geom_raster(data = .x,
                     aes(lon, lat, fill = value)) +
         scale_fill_viridis_c(name = unique(.x$parameter)) +
         facet_grid(decade ~ .))


```


## Decadal offset climatology

```{r climatology_maps_decadal_offset, fig.asp=1}

OceanSODA_clim_decadal_offset <- bind_rows(
  OceanSODA_clim_decadal,
  OceanSODA_clim %>% 
    mutate(decade = "value_clim")
)

OceanSODA_clim_decadal_offset <- OceanSODA_clim_decadal_offset %>% 
  pivot_longer(sal:tco2_over_pCO2,
               names_to = "parameter",
               values_to = "value") %>% 
  select(lat, lon, decade, parameter, value) %>% 
  pivot_wider(names_from = decade,
              values_from = value) %>% 
  pivot_longer(4:6,
               names_to = "decade",
               values_to = "value_decade") %>% 
  mutate(offset = value_decade - value_clim)

OceanSODA_clim_decadal_offset %>%
  group_split(parameter) %>%
  # head(1) %>%
  map( ~ map +
         geom_raster(data = .x,
                     aes(lon, lat, fill = offset)) +
         scale_fill_divergent(name = unique(.x$parameter)) +
         facet_grid(decade ~ .))


```

# Time series

## 5 regions

```{r time_series_5_regions}

OceanSODA_annual_5 %>%
  group_split(parameter) %>%
  # head(1) %>%
  map(
    ~ ggplot(data = .x,
             aes(year, value_area_ave, col = basin)) +
      scale_color_brewer(palette = "Set1") +
      geom_path() +
      geom_point() +
      labs(y = .x$parameter)
  )

```

## Lat bands

```{r time_series}

OceanSODA_annual_lat %>%
  group_split(parameter) %>%
  # head(1) %>%
  map(
    ~ ggplot(data = .x,
             aes(year, value_area_ave, col = lat_bands)) +
      scale_color_brewer(palette = "Spectral") +
      geom_path() +
      geom_point() +
      labs(y = .x$parameter)
  )

```

# Decadel trends

## Global

```{r decadel_trends_glob, fig.asp=0.5}

OceanSODA_annual_glob %>%
  group_split(parameter) %>%
  # head(1) %>%
  map(
    ~ ggplot(data = .x,
             aes(year, value_area_ave, col = decade)) +
      scale_color_brewer(palette = "Set1") +
      geom_point() +
      labs(y = .x$parameter) +
      geom_smooth(method = "lm", se = FALSE)
  )


OceanSODA_annual_glob_trend %>%
  filter(term == "year") %>%
  group_split(parameter) %>%
  # head(1) %>%
  map(
    ~ ggplot(data = .x,
             aes(decade, estimate)) +
      scale_fill_brewer(palette = "Spectral") +
      geom_point(shape = 21) +
      geom_path() +
      labs(y = paste(.x$parameter, "annual change"))
  )

```


## Latitude bands

```{r decadel_trends_lat, fig.asp=0.5}

OceanSODA_annual_lat %>%
  group_split(parameter) %>%
  # head(1) %>%
  map(
    ~ ggplot(data = .x,
             aes(year, value_area_ave, col = decade)) +
      scale_color_brewer(palette = "Set1") +
      geom_point() +
      labs(y = .x$parameter) +
      geom_smooth(method = "lm", se = FALSE) +
      facet_wrap( ~ lat_bands)
  )


OceanSODA_annual_lat_trend %>%
  filter(term == "year") %>%
  group_split(parameter) %>%
  # head(1) %>%
  map(
    ~ ggplot(data = .x,
             aes(decade, estimate, fill = lat_bands)) +
      scale_fill_brewer(palette = "Spectral") +
      geom_point(shape = 21) +
      geom_path() +
      labs(y = paste(.x$parameter, "annual change"))
  )

```


